###
curl -X 'POST' \
  'https://localhost:5014/api/v1/NewPost' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "author": "TEST",
  "message": "BEGIN
    request_id: {{$guid}},
    updated_at: {{$timestamp}},
    created_at: {{$timestamp -1 d}},
    review_count: {{$randomInt 5 200}},
    custom_date: {{$datetime 'YYYY-MM-DD'}},
    local_custom_date: {{$localDatetime iso8601}}
  END
  "
}'
